// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SNAEntityFramework;

namespace SNAEntityFramework.Migrations
{
    [DbContext(typeof(SNADbContext))]
    partial class SNADbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("SNAEntityFramework.Entities.Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AvgFriendsCount")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("LinksCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsersCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("Datasets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvgFriendsCount = 5.3333000000000004,
                            Description = "Sample dataset",
                            LinksCount = 48,
                            Name = "Sample",
                            UsersCount = 18
                        });
                });

            modelBuilder.Entity("SNAEntityFramework.Entities.Link", b =>
                {
                    b.Property<int>("DatasetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("User1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("User2Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("DatasetId", "User1Id", "User2Id");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            DatasetId = 1,
                            User1Id = 0,
                            User2Id = 1
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 0,
                            User2Id = 2
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 0,
                            User2Id = 3
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 0,
                            User2Id = 4
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 0,
                            User2Id = 5
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 0,
                            User2Id = 6
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 0,
                            User2Id = 12
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 1,
                            User2Id = 2
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 1,
                            User2Id = 3
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 1,
                            User2Id = 4
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 1,
                            User2Id = 5
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 2,
                            User2Id = 3
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 2,
                            User2Id = 4
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 2,
                            User2Id = 5
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 3,
                            User2Id = 4
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 3,
                            User2Id = 5
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 4,
                            User2Id = 5
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 6,
                            User2Id = 7
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 6,
                            User2Id = 8
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 6,
                            User2Id = 9
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 6,
                            User2Id = 10
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 6,
                            User2Id = 11
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 6,
                            User2Id = 12
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 7,
                            User2Id = 8
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 7,
                            User2Id = 9
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 7,
                            User2Id = 10
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 7,
                            User2Id = 11
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 8,
                            User2Id = 9
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 8,
                            User2Id = 10
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 8,
                            User2Id = 11
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 9,
                            User2Id = 10
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 9,
                            User2Id = 11
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 10,
                            User2Id = 11
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 12,
                            User2Id = 13
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 12,
                            User2Id = 14
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 12,
                            User2Id = 15
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 12,
                            User2Id = 16
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 12,
                            User2Id = 17
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 13,
                            User2Id = 14
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 13,
                            User2Id = 15
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 13,
                            User2Id = 16
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 13,
                            User2Id = 17
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 14,
                            User2Id = 15
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 14,
                            User2Id = 16
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 14,
                            User2Id = 17
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 15,
                            User2Id = 16
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 15,
                            User2Id = 17
                        },
                        new
                        {
                            DatasetId = 1,
                            User1Id = 16,
                            User2Id = 17
                        });
                });

            modelBuilder.Entity("SNAEntityFramework.Entities.Link", b =>
                {
                    b.HasOne("SNAEntityFramework.Entities.Dataset", "Dataset")
                        .WithMany()
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });
#pragma warning restore 612, 618
        }
    }
}
